import setuptools

with open("README.md", "r") as fh:
    long_description = fh.read()

setuptools.setup(
    name="API REST GildedRose",
    version="0.0.1",
    author="VictorPorlan, CarlosFrancoCifuentes",
    author_email="vporlan@cifpfbmoll.eu, cfranco@cifpfbmoll.eu",
    description="API REST Flask example",
    long_description=long_description,
    long_description_content_type="text/markdown",
    url="https://github.com/CarlosFrancoCifuentes/ApiRest-Ollivanders",
    packages=setuptools.find_packages(),
    include_package_data=True,
    classifiers=[
        "Programming Language :: Python :: 3",
        "License :: OSI Approved :: MIT License",
        "Operating System :: OS Independent",
    ],
    python_requires='>=3.6',
    install_requires=[
        "aniso8601==9.0.1",
        "appdirs==1.4.4",
        "atomicwrites==1.4.0",
        "attrs==20.3.0",
        "click==7.1.2",
        "colorama==0.4.4",
        "distlib==0.3.1",
        "filelock==3.0.12",
        "Flask==1.1.2",
        "Flask-RESTful==0.3.8",
        'iniconfig==1.1.1',
        'itsdangerous==1.1.0',
        'Jinja2==2.11.3',
        'MarkupSafe==1.1.1',
        'mypy-extensions==0.4.3',
        'packaging==20.9',
        'pathspec==0.8.1',
        'pluggy==0.13.1',
        'py==1.10.0',
        'pyparsing==2.4.7',
        'pytest==6.2.2',
        'pytz==2021.1',
        'regex==2021.3.17',
        'six==1.15.0',
        'toml==0.10.2',
        'tox==3.23.0',
        'typed-ast==1.4.2',
        'typing-extensions==3.7.4.3',
        'virtualenv==20.4.3',
        'Werkzeug==1.0.1'
    ],
)